### PR TITLE
Break up raw data initialization of BubbleExample, Fixes #104

### LINKED ISSUE #104: Example broken (XCode 7.3)
SwiftCharts-master/Examples/Examples/BubbleExample.swift:62:11: Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

### PR DESCRIPTION
**Pull request by creister**

### CODE REVIEW

File: Examples/Examples/BubbleExample.swift [hunk 1]
```diff
@@ -32,34 +32,35 @@ class BubbleExample: UIViewController {
...
-            (10, 6, 100, toColor(1)),
-            (11, 7, 100, toColor(0)),
-            (11, 4, 200, toColor(0.5)),
-            (11.5, 10, 150, toColor(0.7)),
-            (12, 7, 120, toColor(0.9)),
-            (12, 9, 250, toColor(0.8))
-            
-        ].map{ChartPointBubble(x: ChartAxisValueDouble(Double($0), labelSettings: labelSettings), y: ChartAxisValueDouble(Double($1)), diameterScalar: $2, bgColor: $3)}
+
+        let rawData: [(Double, Double, Double, UIColor )] = [
```
Comment (i-schuetz) [inline Examples/Examples/BubbleExample.swift]: Can you please remove the space after UIColor? :)

**Comment by creister** [comment]
Ah good catch, I removed the space and updated.

**Comment by i-schuetz** [comment]
Thanks!
